"""create deals table

Revision ID: 36a1a96d8bd3
Revises: f1239813712f
Create Date: 2026-07-15 02:39:58.614180

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36a1a96d8bd3"
down_revision: str | Sequence[str] | None = "f1239813712f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "lead",
                "hearing",
                "proposal",
                "negotiation",
                "closed_won",
                "closed_lost",
                name="dealstatus",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("starter", "professional", "enterprise", name="dealplan"),
            nullable=False,
        ),
        sa.Column("license_count", sa.Integer(), nullable=False),
        sa.Column("contract_period", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deals")
    # ### end Alembic commands ###
